# Generated by Django 5.2.16 on 2026-08-03 12:03

import apps.alumni.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_mandate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='nom du fichier')),
                ('strict', models.BooleanField(default=False, verbose_name='mode strict')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='importé le')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='lignes lues')),
                ('rows_created', models.PositiveIntegerField(default=0, verbose_name='profils créés')),
                ('rows_updated', models.PositiveIntegerField(default=0, verbose_name='profils mis à jour')),
                ('rows_skipped', models.PositiveIntegerField(default=0, verbose_name='lignes sans changement')),
                ('rows_failed', models.PositiveIntegerField(default=0, verbose_name='lignes en erreur')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_imports', to=settings.AUTH_USER_MODEL, verbose_name='importé par')),
            ],
            options={
                'verbose_name': 'import alumni',
                'verbose_name_plural': 'imports alumni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlumniImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='ligne')),
                ('raw_row', models.JSONField(default=dict, verbose_name='ligne brute')),
                ('message', models.TextField(verbose_name='message')),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='alumni.alumniimport', verbose_name='import')),
            ],
            options={
                'verbose_name': 'ligne en erreur',
                'verbose_name_plural': 'lignes en erreur',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('promotion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(apps.alumni.models.promotion_max)], verbose_name='promotion')),
                ('country', models.CharField(default='Bénin', max_length=100, verbose_name='pays')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='université')),
                ('mcf_program', models.CharField(blank=True, max_length=200, verbose_name='programme MCF')),
                ('sector', models.CharField(blank=True, choices=[('agriculture', 'Agriculture et agro-industrie'), ('sante', 'Santé'), ('education', 'Éducation et formation'), ('numerique', 'Technologies et numérique'), ('finance', 'Finance et assurance'), ('entrepreneuriat', 'Entrepreneuriat et PME'), ('energie', 'Énergie et environnement'), ('industrie', 'Industrie et BTP'), ('commerce', 'Commerce et distribution'), ('transport', 'Transport et logistique'), ('public', 'Administration publique'), ('ong', 'Société civile et ONG'), ('culture', 'Arts, culture et médias'), ('recherche', 'Recherche'), ('autre', 'Autre')], max_length=50, verbose_name="secteur d'activité")),
                ('current_position', models.CharField(blank=True, max_length=200, verbose_name='poste actuel')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='organisation')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='profil LinkedIn')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('femme', 'Femme'), ('homme', 'Homme'), ('autre', 'Autre'), ('non_precise', 'Non précisé')], max_length=20, verbose_name='genre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('directory_consent', models.BooleanField(default=False, verbose_name="publication dans l'annuaire")),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='actif', max_length=10, verbose_name='statut')),
                ('source', models.CharField(choices=[('inscription', 'Inscription en ligne'), ('import', 'Import')], default='inscription', max_length=15, verbose_name='origine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('mandate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_profiles', to='accounts.mandate', verbose_name='mandat')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte')),
            ],
            options={
                'verbose_name': 'profil alumni',
                'verbose_name_plural': 'profils alumni',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AlumniRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse e-mail')),
                ('promotion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(apps.alumni.models.promotion_max)], verbose_name='promotion')),
                ('country', models.CharField(default='Bénin', max_length=100, verbose_name='pays')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='université')),
                ('mcf_program', models.CharField(blank=True, max_length=200, verbose_name='programme MCF')),
                ('sector', models.CharField(blank=True, choices=[('agriculture', 'Agriculture et agro-industrie'), ('sante', 'Santé'), ('education', 'Éducation et formation'), ('numerique', 'Technologies et numérique'), ('finance', 'Finance et assurance'), ('entrepreneuriat', 'Entrepreneuriat et PME'), ('energie', 'Énergie et environnement'), ('industrie', 'Industrie et BTP'), ('commerce', 'Commerce et distribution'), ('transport', 'Transport et logistique'), ('public', 'Administration publique'), ('ong', 'Société civile et ONG'), ('culture', 'Arts, culture et médias'), ('recherche', 'Recherche'), ('autre', 'Autre')], max_length=50, verbose_name="secteur d'activité")),
                ('current_position', models.CharField(blank=True, max_length=200, verbose_name='poste actuel')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='organisation')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='profil LinkedIn')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('femme', 'Femme'), ('homme', 'Homme'), ('autre', 'Autre'), ('non_precise', 'Non précisé')], max_length=20, verbose_name='genre')),
                ('directory_consent', models.BooleanField(default=False, verbose_name="publication dans l'annuaire")),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=12, verbose_name='statut')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='soumise le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='instruite le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif du rejet')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='alumni.alumniprofile', verbose_name='profil créé')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_reviews', to=settings.AUTH_USER_MODEL, verbose_name='instruite par')),
            ],
            options={
                'verbose_name': "demande d'inscription alumni",
                'verbose_name_plural': "demandes d'inscription alumni",
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'en_attente')), fields=('email',), name='unique_demande_en_attente_par_email')],
            },
        ),
    ]
