# Generated by Django 5.2.15 on 2026-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='mandat courant')),
            ],
            options={
                'verbose_name': 'mandat',
                'verbose_name_plural': 'mandats',
                'ordering': ['-start_date'],
            },
        ),
    ]
