# Generated by Django 5.2.15 on 2026-08-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=12, verbose_name='statut')),
                ('provider', models.CharField(default='manual', max_length=50, verbose_name='fournisseur')),
                ('provider_reference', models.CharField(blank=True, max_length=255, verbose_name='référence fournisseur')),
                ('reference', models.CharField(max_length=64, unique=True, verbose_name='référence interne')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
